### ISSUE TITLE
Version for Module Loader

### ISSUE THREAD

**Issue by Mariyo** [esimonetti/SugarAdvancedWorkflowCustomPHPMethods#1]
Hello,

first of all, thank you for this example!

I have just one proposal, could you prepare .zip with manifest and all files in this example, which will be possible to install via Module Loader?

Thank you,
Mariyo

**Comment by esimonetti** [comment]
Hi Mariyo,

Not a problem!

Given that the logic needs to be modified and customised based on the specific needs (https://github.com/esimonetti/SugarAdvancedWorkflowCustomPHPMethods/blob/master/custom/modules/pmse_Project/AWFCustomActionLogic.php), I do not think that providing an installable version of my sample will make much sense.

You could quite easily make your changes installable by leveraging: https://github.com/esimonetti/SugarModulePackager and  an example of its usage here: https://github.com/esimonetti/SugarModulePackagerSample

Hope it helps!
